version: '3.8'
services:
  mysql:
    profiles:
      - all
      - db
    build: ./docker/mysql
    restart: always
    environment:
      MYSQL_DATABASE: mars
      MYSQL_USER: mars
      MYSQL_PASSWORD: mars
      MYSQL_ROOT_PASSWORD: mars
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    ports:
      - "13306:3306"
  mysql-test:
    profiles:
      - all
      - db
    build: ./docker/mysql
    restart: always
    environment:
      MYSQL_DATABASE: mars
      MYSQL_USER: mars
      MYSQL_PASSWORD: mars
      MYSQL_ROOT_PASSWORD: mars
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    ports:
      - "13307:3306"
